# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Release

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:

  binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Generate embed files
      run: go generate

    - name: Build
      uses: thatisuday/go-cross-build@v1
      with:
        platforms: "linux/amd64, linux/arm64, darwin/amd64, windows/amd64"
        package: ""
        name: "BungieAlerter"
        compress: "false"
