name: Build Release

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  workflow_dispatch:

env:
  BINARY_NAME: "BungieAlerter"

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: 0
        
    - name: Bump version and push tag
      id: version_bump
      uses: anothrNick/github-tag-action@1.61.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: None

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Generate embed files
      run: go generate
    
    - name: Build linux/amd64
      run: go build -ldflags "-s -w" -o bin/$BINARY_NAME-linux-amd64 .
    
    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*"
        omitBody: true
        makeLatest: true
        commit: ${{ github.sha }}
        tag: ${{ steps.version_bump.outputs.new_tag }}
