name: Build Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:

env:
  BINARY_NAME: "BungieAlerter"

jobs:
  binaries:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Generate embed files
      run: go generate
    
    - name: Build linux/amd64
      run: go build -ldflags "-s -w" -o bin/$BINARY_NAME-linux-amd64 .
    
    - name: Publish release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "bin/*"
        omitBody: "true"
        makeLatest: "true"
